### PR TITLE
Material.css: Override opblock h4 span:after color

### PR DESCRIPTION
**Pull request by gracefullight**
image

### CODE REVIEW

**Comment by ostranme** [comment]
I'll review here soon - just haven't had time to pull down and test it out. Do you know if this change needs to be added for the other themes, or is this specific to the material theme?

**Comment by gracefullight** [comment]
@ostranme specific to the material theme 😄

**Comment by heldersepu** [comment]
Any update on this?

**Comment by ostranme** [comment]
@heldersepu @gracefullight Sorry for the delay I've been busy after the new year. I'll merge this in this week. I'm going to have to add the same overrides to the rest of the themes as well. Thanks!

**Comment by heldersepu** [comment]
Thanks @ostranme

**Comment by heldersepu** [comment]
@ostranme  I just incorporated all your themes into [Swagger-Net](https://github.com/heldersepu/Swagger-Net):
- http://swagger-net-test.azurewebsites.net/swagger/ui/index?cssTheme=theme-feeling-blue-css
- http://swagger-net-test.azurewebsites.net/swagger/ui/index?cssTheme=theme-flattop-css
- http://swagger-net-test.azurewebsites.net/swagger/ui/index?cssTheme=theme-material-css

**Comment by ostranme** [comment]
Looks great! 😄

**Pull request merged**
